package cn.itcast.nsfw.complain.entity;
// Generated 2018-1-26 10:27:07 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ComplainReply generated by hbm2java
 */
@Entity
@Table(name = "complain_reply")
public class ComplainReply implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String replyId;
	private Complain compId;
	private String replyer;
	private String replyDept;
	private Date replyTime;
	private String replyContent;

	public ComplainReply() {
	}

	public ComplainReply(String replyId, Complain compId) {
		this.replyId = replyId;
		this.compId = compId;
	}

	public ComplainReply(String replyId, Complain compId, String replyer, String replyDept, Date replyTime,
			String replyContent) {
		this.replyId = replyId;
		this.compId = compId;
		this.replyer = replyer;
		this.replyDept = replyDept;
		this.replyTime = replyTime;
		this.replyContent = replyContent;
	}

	@Id
	@Column(name = "reply_id", unique = true, nullable = false, length = 32)
	@GenericGenerator(name="replyid",strategy="uuid")
	@GeneratedValue(generator="replyid")
	public String getReplyId() {
		return this.replyId;
	}

	public void setReplyId(String replyId) {
		this.replyId = replyId;
	}

	@ManyToOne
	@JoinColumn(name = "comp_id", nullable = false)
	public Complain getCompId() {
		return this.compId;
	}

	public void setCompId(Complain compId) {
		this.compId = compId;
	}

	@Column(name = "replyer", length = 20)
	public String getReplyer() {
		return this.replyer;
	}

	public void setReplyer(String replyer) {
		this.replyer = replyer;
	}

	@Column(name = "reply_dept", length = 100)
	public String getReplyDept() {
		return this.replyDept;
	}

	public void setReplyDept(String replyDept) {
		this.replyDept = replyDept;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reply_time", length = 19)
	public Date getReplyTime() {
		return this.replyTime;
	}

	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}

	@Column(name = "reply_content", length = 300)
	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

}
