package cn.itcast.nsfw.complain.entity;
// Generated 2018-1-26 10:27:07 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Complain generated by hbm2java
 */
@Entity
@Table(name = "complain")
public class Complain implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String compId;
	private String compCompany;
	private String compName;
	private String compMobile;
	private Boolean isNm;
	private Date compTime;
	private String compTitle;
	private String toCompName;
	private String toCompDept;
	private String compContent;
	private String state;
	
	private List<ComplainReply> complainReplies;
	
	//状态
	public static String COMPLAIN_STATE_UNDONE = "0";
	public static String COMPLAIN_STATE_DONE = "1";
	public static String COMPLAIN_STATE_INVALID = "2";
	public static Map<String, String> COMPLAIN_STATE_MAP;
	static {
		COMPLAIN_STATE_MAP = new HashMap<String, String>();
		COMPLAIN_STATE_MAP.put(COMPLAIN_STATE_UNDONE, "待受理");
		COMPLAIN_STATE_MAP.put(COMPLAIN_STATE_DONE, "已受理");
		COMPLAIN_STATE_MAP.put(COMPLAIN_STATE_INVALID, "已失效");
	}

	public Complain() {
	}

	public Complain(String compId, String compTitle) {
		this.compId = compId;
		this.compTitle = compTitle;
	}

	public Complain(String compId, String compCompany, String compName, String compMobile, Boolean isNm, Date compTime,
			String compTitle, String toCompName, String toCompDept, String compContent, String state) {
		this.compId = compId;
		this.compCompany = compCompany;
		this.compName = compName;
		this.compMobile = compMobile;
		this.isNm = isNm;
		this.compTime = compTime;
		this.compTitle = compTitle;
		this.toCompName = toCompName;
		this.toCompDept = toCompDept;
		this.compContent = compContent;
		this.state = state;
	}

	@Id
	@Column(name = "comp_id", unique = true, nullable = false, length = 32)
	@GenericGenerator(name="compid",strategy="uuid")
	@GeneratedValue(generator="compid")
	public String getCompId() {
		return this.compId;
	}

	public void setCompId(String compId) {
		this.compId = compId;
	}

	@Column(name = "comp_company", length = 100)
	public String getCompCompany() {
		return this.compCompany;
	}

	public void setCompCompany(String compCompany) {
		this.compCompany = compCompany;
	}

	@Column(name = "comp_name", length = 20)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@Column(name = "comp_mobile", length = 20)
	public String getCompMobile() {
		return this.compMobile;
	}

	public void setCompMobile(String compMobile) {
		this.compMobile = compMobile;
	}

	@Column(name = "is_NM")
	public Boolean getIsNm() {
		return this.isNm;
	}

	public void setIsNm(Boolean isNm) {
		this.isNm = isNm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comp_time", length = 19)
	public Date getCompTime() {
		return this.compTime;
	}

	public void setCompTime(Date compTime) {
		this.compTime = compTime;
	}

	@Column(name = "comp_title", nullable = false, length = 200)
	public String getCompTitle() {
		return this.compTitle;
	}

	public void setCompTitle(String compTitle) {
		this.compTitle = compTitle;
	}

	@Column(name = "to_comp_name", length = 20)
	public String getToCompName() {
		return this.toCompName;
	}

	public void setToCompName(String toCompName) {
		this.toCompName = toCompName;
	}

	@Column(name = "to_comp_dept", length = 100)
	public String getToCompDept() {
		return this.toCompDept;
	}

	public void setToCompDept(String toCompDept) {
		this.toCompDept = toCompDept;
	}

	@Column(name = "comp_content", length = 65535)
	public String getCompContent() {
		return this.compContent;
	}

	public void setCompContent(String compContent) {
		this.compContent = compContent;
	}

	@Column(name = "state", length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	@OneToMany(targetEntity=ComplainReply.class,fetch=FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name="comp_id")
	public List<ComplainReply> getComplainReplies() {
		return complainReplies;
	}

	public void setComplainReplies(List<ComplainReply> complainReplies) {
		this.complainReplies = complainReplies;
	}

}
